class ConfigDefaults:
    # DATABASE CONNECTION SETTINGS
    MYSQL_HOST = 'localhost'
    MYSQL_DB_SCHEMA = 'generator'
    MYSQL_USER = 'root'
    MYSQL_PASS = 'root'

    # ERRORS
    LOG_FILE_WRITING_ERROR = 1
    QUERY_FILE_WRITING_ERROR = 2
    QUERY_FILE_READING_ERROR = 3
    MEMORY_ERROR = 4
    ZERO_BATCHES_ERROR = 5

    # DELAYS
    WAIT_AFTER = 10
    WAIT_BEFORE = -10

    # FILE PATHS
    QUERY_FILE_PATH = 'QUERIES.txt'
    LOG_FILE_PATH = 'LOG.txt'
    REPORT_FILE_PATH = 'REPORT.txt'

    # LOGGING LEVEL
    LOG_LEVEL = 4

    # ID PIECES
    FIRST_ID_PART = 3333
    SECOND_ID_PART = 2222
    THIRD_ID_PART = 4444
    FOURTH_ID_PART = 1111

    # TAG START VALUES
    FIRST_TAG = 4
    SECOND_TAG = 8
    THIRD_TAG = 7
    FOURTH_TAG = 6
    FIFTH_TAG = 11

    # FIRST CURRENCY PAIR
    FIRST_PAIR = 10

    # ZONES SPREAD
    RED = 15 / 100
    GREEN = 6 / 10
    BLUE = 25 / 100

    # BATCH CONFIGURATION
    BATCH_SIZE = 200
    BATCHES_AMOUNT = 10

    # START DESC
    FIRST_DESC = 164

    # START TIME (UNIX TIMESTAMP)
    BEGINNING_OF_TIME = 1540000000

    # ID GENERATION DEFAULTS
    ID_MULT = 3
    ID_OFFSET = 2
    ID_DIV = 4000

    # TAGS GENERATION DEFAULTS
    TAGS_MULT = 3
    TAGS_OFFSET = 4
    TAGS_DIV = 25

    # DESC GENERATION DEFAULTS
    DESC_MULT = 5
    DESC_OFFSET = 4
    DESC_DIV = 999

    # CURPAIR GENERATION DEFAULTS
    CURPAIR_MULT = 1
    CURPAIR_OFFSET = 2
    CURPAIR_DIV = 15

    # PRICE MARGINS
    INIT_MARGIN = 6 / 100
    FILL_MARGIN = 5 / 100

    # PROBABILITIES FOR PPF FUNCTION
    INIT_LESS = 3 / 10
    INIT_MORE = 7 / 10
    FILL_LESS = 4 / 10
    FILL_MORE = 6 / 10

    # ROUND PARAMS
    PLACES_FOR_PRICE = 5
    PLACES_FOR_VOLUME = 8

    # TAG COUNT
    TAG_AMOUNT = 11
